export { AboutUsPage } from './AboutUsPage/AboutUsPage';
export { CatalogPage } from './CatalogPage/CatalogPage';
export { ErrorPage } from './ErrorPage/ErrorPage';
export { MainPage } from './MainPage/MainPage';
export { ProductPage } from './ProductPage/ProductPage';
export { RegistrationPage } from './RegistrationPage/RegistrationPage';
export { ShoppingCartPage } from './ShoppingCartPage/ShoppingCartPage';
export { SignInPage } from './SignInPage/SignInPage';
export { UserProfilePage } from './UserProfilePage/UserProfilePage';
