export enum UrlPath {
  HOME = '/',
  SIGN_IN = '/sign-in',
  REGISTRATION = 'registration',
  CATALOG = 'catalog',
  CATALOG_ALL = 'catalog/all',
  ABOUT = 'about',
  USER_PROFILE = '/user-profile',
  USER_PROFILE_CREDENTIALS = 'credentials',
  USER_PROFILE_ADDRESSES = 'addresses',
  USER_PROFILE_CHANGE_PASSWORD = 'change-password',
  SHOPPING_CART = 'shopping-cart',
  PRODUCT = 'product',
  NOT_FOUND = '*',
}
